### ISSUE TITLE
_official-realtime-app can't be run

### ISSUE THREAD

**Issue by SylRob** [remix-run/examples#106]
Hi, when I run the example I get the error 
```
node: bad option: --watch
ERROR: "dev:server" exited with 9.
```

my node version is 18.9.1

way to reproduce the error
```
npm install
npm run dev
```

**Comment by machour** [comment]
The example requires Node 19

**Comment by MichaelDeBoey** [comment]
@ryanflorence Can we rewrite the code to make it work on Node v14?

**Comment by daniserrano7** [comment]
To make it work, I changed it to 

"dev": "concurrently \"npm run dev:css\" \"remix dev\""

I use Node.js 16.15.0

**Comment by MichaelDeBoey** [comment]
@SylRob Could you please try again now that we have #126 merged?

**Comment by SylRob** [comment]
@MichaelDeBoey , nop still same for me.
pulled from `main` main branch, deleted `node_module/`, `npm install`, `npm run dev` 
```
node: bad option: --watch
ERROR: "dev:server" exited with 9.
```

**Comment by machour** [comment]
@SylRob what node version are you using?

**Comment by SylRob** [comment]
@machour still v18.9.1

**Comment by machour** [comment]
The errors says:

```
node: bad option: --watch
```

`--watch` is used in the package.json's commands.

That option was [introduced in v18.11.0](https://nodejs.org/en/blog/release/v18.11.0/), so it's not compatible with your node version.

So you can either update your node version to finally be able to make this example work for you, or you can change the commands as @daniserrano7 did to make it work on your current version.

If you do the later, please open a pull requests with your changes so that we can merge it and have this work for node < 18.11

**Comment by machour** [comment]
No worries. 
But I rather have the example made compatible with more node versions, instead of requiring a specific one

**Comment by SylRob** [comment]
Yes that is true, but if the targeted version is the node v14, I will not be able to test it, since I can only propose a (possible) working and tested version using @daniserrano7 proposal and my 18.9 ...
