### ISSUE TITLE
Redirect param in /new route

### ISSUE THREAD

**Issue by AxelBriche** [remix-run/examples#54]
Inside the `/new.tsx` file, I have find this line of code : `return redirect(`/threads/${thread.id}?redirectTo=/threads/new`);`
What is `?redirectTo` inside that redirection? The Joke tutorial on the remix site don't have this url param.

**Comment by machour** [comment]
Hi, I looked for the term "thread" in all examples but couldn't find it.

Could you please post your question again in the "Q&A" categories of our [GitHub discussions](https://github.com/remix-run/remix/discussions/new) giving a little more details about the example you're talking about and a link to the file? 🙏🏼  

This issues tab is meant to be used to report bugs with the examples, or ask for new ones.

(My guess it's a parameter that is read by the target route, in order to redirect after login, or something 🤷🏼‍♂️ )

**Comment by AxelBriche** [comment]
Sorry for the error, you can search `?redirectTo=/jokes/new`
